### PR TITLE
Upgrade axum integration to Axum 0.2.0

### PR DESCRIPTION
**Pull request by shanesveller**
I'm not an experienced Rust developer yet, so this is mostly just some brute-force follow-the-compiler changes that I can build and test successfully and incorporate into a personal project with successful build and test. Please feel free to keep or discard anything you like, I just wanted to offer a starting point and volunteer to try to see it through with some guidance. I'll gladly follow any contributor guidelines you can point me to, as well.

### CODE REVIEW

**Comment by shanesveller** [comment]
I also referred to https://github.com/tokio-rs/axum/pull/234 for the trait bounds change.

**Comment by sunli829** [comment]
Thank you for your PR👏, if you are done, please let me know.
There are examples for testing in the [examples](https://github.com/async-graphql/examples/tree/fec86ff7383b64375fa1ca0a4e7fdcffd6417086/poem) directory.

**Comment by shanesveller** [comment]
@sunli829 I've opened https://github.com/async-graphql/examples/pull/41 to address the CI failure. Other than potentially you or I updating the submodule rev, I think I'm done making changes pending any incoming feedback, so I'll take this PR out of draft status. Thanks for your attention!

**Comment by sunli829** [comment]
Thank you for your excellent work! @shanesveller

**Comment by Voxelot** [comment]
Looks like CI is failing now?

**Comment by Miaxos** [comment]
He knows, It's not related: https://github.com/async-graphql/async-graphql/pull/615#issuecomment-909736947

**Comment by sunli829** [comment]
I'm working on it.

**Comment by sunli829** [comment]
`Async-graphql-axum` has been released. https://crates.io/crates/async-graphql-axum

Many thanks! @shanesveller 👏🏻

**Pull request merged**
