### PR TITLE
Implement OutputValueType for FieldResult

### PR DESCRIPTION
**Pull request by IcanDivideBy0**
Hello,
While using async_graphql I've came across several usecase where it's useful to return a FieldResult as an output type:

1. ` -> Option<FieldResult<_>>`
1. ` -> Vec<FieldResult<_>>`
1. ` -> impl Stream<Item = FieldResult<_>>`

While the first two can be easily handled by swaping things around, the third one is a bit more tricky.

In the actual implementation, when a field fail, only the error is returned even if other fields resloved successfuly, so the first two usecase don't have much sense in this context.

When using subscriptions tho, many thing can occurs during the stream (database connection being lost for example) and right now I can't figure a way to send those errors to the client.

This PR is not really intended to be merged as is, I'd like to first discuss those usecases with you folks and get some feedback on what you think about it. Also while I tested this implementation, I've noticed the error path is lost in the response, so there's definilty more to do here.

### CODE REVIEW

**Comment by sunli829** [comment]
I'm actually adding this feature, and I've already done some of it.😁
I thought FieldResult's implementation of OutputValueType was a good idea, but I ran into some problems with code generation at the time, and now I'll try the possibility again.

**Comment by sunli829** [comment]
I made some initial attempts and this should be done quickly. 😁

**Comment by sunli829** [comment]
I've completed this feature  in `1.10.4` version, and you mentioned that the third problem was solved in the previous release, so I only need to implement `Type` and `OutputType` for FieldResult to solve all the problems.

Thank you for your suggestions.😁

**Comment by IcanDivideBy0** [comment]
TBH I'm really amazed by how fast you always respond on this project an the tremendous amount and quality of work you already produced!

**Pull request closed without merging**
