### PR TITLE
Add minimum rust version support in workflow

### LINKED ISSUE #468: Minimum version is now 1.49.0?
## Expected Behavior

Compiling on Rust 1.46.0 succeeds.

## Actual Behavior

Compilation fails about some unstable feature regarding some library getting pulled in using [spinloop](https://doc.rust-lang.org/std/hint/fn.spin_loop.html), which did not stabilize until 1.49.0. This seems to be due to a newer version of a library being pulled in as part of async_graphql, even on older versions such as 2.4.6.

```
error[E0658]: use of unstable library feature 'renamed_spin_loop'
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.9.0/src/relax.rs:26:9
   |
26 |         core::hint::spin_loop();
   |         ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error: aborting due to previous error
```

## Steps to Reproduce the Problem

1. Install Rust 1.46.0 via `rustup toolchain install --minimal 1.46.0`
2. Create some project that uses async_graphql (version 2.4.6 or greater? not sure how far back it goes)
3. Attempt to compile via `cargo +1.46.0 build`

## Specifications

- Version: 2.7.4 (although this started happening for me with older versions all the way back to 2.4.6)
- Platform: Windows/Linux/Mac
- Subsystem: ???

### PR DESCRIPTION
**Pull request by chipsenkbeil**
Resolves #468 by adding tests for the minimum version of Rust that async graphql supports.

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
@sunli829, looks like something is getting pulled in now that even version 1.49.0 isn't acceptable anymore. I'll try bumping up and see what works, but to my knowledge 1.49.0 was working earlier.

**Comment by chipsenkbeil** [comment]
@sunli829, version 1.50.0 is giving errors with clippy about missing stuff, I'll try to bump to the latest version, but seems odd that the most recent version of Rust would be needed.

**Comment by chipsenkbeil** [comment]
Okay, 1.49.0 still fails tests because it can't compile due to an unstable feature brought in by the state library. Switching back to 1.50.0 to see if that passes tests while clippy and rustfmt stick with only running on Rust stable.

**Comment by sunli829** [comment]
Thank you so much! I'm going to merge later because there are a lot of changes on my side. 😅

**Comment by chipsenkbeil** [comment]
@sunli829, no worries! Just happy to help. It looks like version 1.50.0 is the minimum version prior to any changes you add.

Interestingly, we hit a compiler bug in nightly with my last push. 😆 If you look at the output

```
error: internal compiler error: compiler/rustc_mir/src/transform/generator.rs:751:13: Broken MIR: generator contains type Pin<Box<dyn std::future::Future<Output = std::result::Result<response::Response, http_types::Error>> + std::marker::Send>> in MIR, but typeck only knows about for<'r, 's, 't0> {ResumeTy, &'r F, request::Request<State>, middleware::Next<'s, State>, Pin<Box<(dyn std::future::Future<Output = std::result::Result<response::Response, http_types::Error>> + std::marker::Send + 't0)>>, ()}
  --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.16.0/src/middleware.rs:35:89
   |
35 |       async fn handle(&self, req: Request<State>, next: Next<'_, State>) -> crate::Result {
   |  _________________________________________________________________________________________^
36 | |         (self)(req, next).await
37 | |     }
   | |_____^

thread 'rustc' panicked at 'Box<Any>', /rustc/138fd56cf9598b4bf016634c768dca128a83a5d7/library/std/src/panic.rs:59:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (138fd56cf 2021-04-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `middleware::<impl at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.16.0/src/middleware.rs:24:1: 38:2>::handle::{closure#0}`
#1 [layout_raw] computing layout of `[static generator@/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.16.0/src/middleware.rs:35:89: 37:6 for<'r, 's, 't0> {std::future::ResumeTy, &'r F, request::Request<State>, middleware::Next<'s, State>, std::pin::Pin<std::boxed::Box<(dyn std::future::Future<Output = std::result::Result<response::Response, http_types::Error>> + std::marker::Send + 't0)>>, ()}]`
end of query stack
error: aborting due to previous error
```

**Pull request merged**
