### PR TITLE
Add Apollo Federation `@inaccessible` directive support

### PR DESCRIPTION
**Pull request by nmoutschen**
This adds the Apollo Federation `@inaccessible` directive support for all supported locations (FIELD_DEFINITION, INTERFACE, OBJECT, UNION, ARGUMENT_DEFINITION, SCALAR, ENUM, ENUM_VALUE, INPUT_OBJECT, INPUT_FIELD_DEFINITION), which brings us one step closer for the issue https://github.com/async-graphql/async-graphql/issues/982.

This also adds a test to validate the ability to inject the directive in all supported locations.

~~(In draft until I update the docs)~~ Updated the docs

### CODE REVIEW

**Comment by nmoutschen** [comment]
Updated the docs as well! Let me know if there's anything I should change or that I missed before this is good to merge 😄

**Comment by sunli829** [comment]
Thank you so much, never thought anyone could help with this! ♥

**Comment by sunli829** [comment]
should use nightly rustfmt to format code 🙂

```rust
cargo +nightly fmt
```

**Comment by nmoutschen** [comment]
Glad to help there! 😄 I just installed the latest nightly toolchain and ran `cargo +nightly fmt`, hopefully this should fix everything

**Pull request merged**
