### PR TITLE
dedupe error handling

### PR DESCRIPTION
**Pull request by mxfactorial**
just let websocket handle it

### CODE REVIEW

**Comment by sunli829** [comment]
When `sink.send` fails, it means the websocket has been closed, and I understand that the next call to `stream.next` will also return an error and end the loop, but I want to know the benefit of doing this. 🙂

**Comment by mxfactorial** [comment]
> but I want to know the benefit of doing this

you preserve the protocol

which is helpful when
1. your client sends a [stop](https://github.com/async-graphql/async-graphql/blob/7a1391bd8539e0581fe7c0cd371a0d38718e5aea/src/http/websocket.rs#L385)
2. but your subscription resolver polls so aggressively that its blocked from reading the stop (fixed by a [10 milli sleep](https://github.com/systemaccounting/mxfactorial/blob/cbcd813d71ccd496cf16d44f162ca5c326d02cdc/services/graphql/src/main.rs#L240))
3. then the client stops accepting messages
4. and the axum integration breaks the subscription because it receives an error instead of a stop

now your debug statement in the stop branch of the websocket submodule doesnt print because of the early termination (debug lines highlighted @[1:00](https://drive.google.com/file/d/1Dnfthd7-rUgybnDMxsbvRi04mqRdhnNI/view) dont print)

so you ask yourself "wheres my stop"

**Comment by sunli829** [comment]
Maybe you should use an [asynchronous WebSocket client](https://docs.rs/websocket/0.27.1/websocket/client/async/index.html), `measure_socket.read()` blocks polling and this can cause weird things to happen.

**Comment by mxfactorial** [comment]
will consider that as an improvement to the sleep thank you

**Comment by sunli829** [comment]
I believe that all the problems you encounter are solved when you use asynchronous WebSocket client. 🙂

**Comment by mxfactorial** [comment]
this pr intends preventing the integration from violating the protocol when weird things happen

and youve received evidence of how others can benefit when the protocol remains

but this is your project and the choice to extend that benefit to others is yours

welcome to close if you prefer not to

**Comment by sunli829** [comment]
I can't reproduce the problem, when the client sends `Stop`, everything works fine, you can test it with this example.

https://github.com/async-graphql/examples/tree/8f0450eec914aa546e5a36c67586b01cf8ffe087/axum/subscription

**Comment by mxfactorial** [comment]
can join you in the rabbit hole of producing another blocking subscription

but easier if you just run your tests with my change and merge the reduction in error handling on [principle](https://en.wikipedia.org/wiki/Single-responsibility_principle)

**Comment by sunli829** [comment]
Does the problem still exist after switching to an asynchronous WebSocket client?

**Comment by mxfactorial** [comment]
doesnt matter

please merge to remove duplicate error handling and unnecessary filter

or close if you judge your code to be an exception to principle

**Comment by sunli829** [comment]
I'm closed this PR because I think the current implementation follows the protocol, feel free to open it again if you have any questions.

**Pull request closed without merging**
