### PR TITLE
Rework guard

### PR DESCRIPTION
**Pull request by AurelienFT**
Refer to #293

### CODE REVIEW

**Comment by AurelienFT** [comment]
@sunli829 If you have some times I would like to have a little bit of help. I want to implement the chain operator which work like the guard system currently implemented on master. But I want to implement it with a vec of rules not a chain of and operator like now.

I know how to it in the parsing system (in derive subfolder) but I don't understand how to implement the operator in `src/guard.rs` which take `Vec<Guard>` has parameter.

If you can provide me some help it will be really cool !

**Comment by sunli829** [comment]
Hmm, is it possible to implement `Guard` for `Vec<T:Guard>`?
But it would be better if you could not use `Vec`? 😂

**Comment by AurelienFT** [comment]
Do you think it's better to chain the `and` operator with two rules than doing a Vector of rule ?

**Comment by sunli829** [comment]
> Do you think it's better to chain the `and` operator with two rules than doing a Vector of rule ?

Yes, I think this can avoid additional memory allocation and dynamic dispatch. 😁

**Comment by AurelienFT** [comment]
Ok I will implement it that way so. Thanks you

**Comment by sunli829** [comment]
> Ok I will implement it that way so. Thanks you

Because `guard` is created every time the `resolver` function is called, right?

**Comment by AurelienFT** [comment]
> > Ok I will implement it that way so. Thanks you
> 
> Because `guard` is created every time the `resolver` function is called, right?

`Guard` macro is expended on the code of the `resolve_field` function so, if I understand well, it's created one time at the creation of the field resolver. Like this (example of expanded `resolve_field`) : 
```
impl async_graphql::resolver_utils::ContainerType for Query {
                fn resolve_field<'life0, 'life1, 'life2, 'async_trait>(
                    &'life0 self,
                    ctx: &'life1 async_graphql::Context<'life2>,
                ) -> ::core::pin::Pin<
                    Box<
                        dyn ::core::future::Future<
                                Output = async_graphql::ServerResult<
                                    ::std::option::Option<async_graphql::serde_json::Value>,
                                >,
                            > + ::core::marker::Send
                            + 'async_trait,
                    >,
                >
                where
                    'life0: 'async_trait,
                    'life1: 'async_trait,
                    'life2: 'async_trait,
                    Self: 'async_trait,
                {
                    #[allow(
                        unused_parens,
                        clippy::missing_docs_in_private_items,
                        clippy::needless_lifetimes,
                        clippy::ptr_arg,
                        clippy::trivially_copy_pass_by_ref,
                        clippy::type_repetition_in_bounds,
                        clippy::used_underscore_binding
                    )]
                    async fn __resolve_field(
                        _self: &Query,
                        ctx: &async_graphql::Context<'_>,
                    ) -> async_graphql::ServerResult<
                        ::std::option::Option<async_graphql::serde_json::Value>,
                    > {
                        if ctx.item.node.name.node == "value" {
                            async_graphql::guard::GuardExt::and(
                                RoleGuard {
                                    role: (Role::Admin).into(),
                                },
                                UserGuard {
                                    username: ("test").into(),
                                },
                            )
                            .check(ctx)
                            .await
                            .map_err(|err| err.into_server_error().at(ctx.item.pos))?;
                            let res = _self
                                .value(ctx)
                                .await
                                .map_err(|err| err.into_server_error().at(ctx.item.pos))?;
```

**Comment by sunli829** [comment]
Yes, but this creation code runs every time it resolves the field.

发自我的iPhone

**Comment by AurelienFT** [comment]
> Yes, but this creation code runs every time it resolves the field.

Yes it runs at each call of the resolver. You think vector gonna need too much ressources ?

**Comment by sunli829** [comment]
> > Yes, but this creation code runs every time it resolves the field.
> 
> Yes it runs at each call of the resolver. You think vector gonna need too much ressources ?

Not much, but there will always be some loss. 😁

**Comment by AurelienFT** [comment]
Ready, reviews are welcome

**Comment by sunli829** [comment]
Thank you very much!
Could you please add a chapter `guard.md` to the `book`? 😀

**Comment by AurelienFT** [comment]
Done.

**Comment by sunli829** [comment]
Thank you so much! 😃

**Pull request merged**
