### PR TITLE
Add cursor getter to connection::Edge

### PR DESCRIPTION
**Pull request by meh**
I need it :panda_face:

### CODE REVIEW

**Comment by sunli829** [comment]
I've added `cursor` method to borrow the cursor value on the Edge, do you need `into_cursor` to get the ownership?

```rust
impl<Cursor, Node, Name> Edge<Cursor, Node, EmptyFields, Name>
where
    Cursor: CursorType + Send + Sync,
    Node: OutputType,
    Name: EdgeNameType,
{
    ....

    /// Returns the cursor of this edge
    pub fn cursor(&self) -> &Cursor {
        &self.cursor.0
    }
}
```

**Comment by sunli829** [comment]
I've removed `CursorScalar` and exposed `Edge::cursor` 🙂

**Comment by sunli829** [comment]
released in `v5.0.10`

**Comment by meh** [comment]
Thanks a bunch!

**Pull request closed without merging**
