### PR TITLE
Add Input / Output for Box<[T]> and Output for Arc<[T]>.

### PR DESCRIPTION
**Pull request by BratSinot**
Solves #805.
P.S. I don't see reason to implement an Input type for `Arc`, because of you can't create `Arc<[T]>` from array / vector without copying data.

### CODE REVIEW

**Comment by sunli829** [comment]
Sorry, I added this to the master branch but forgot to tell you.

**Comment by sunli829** [comment]
Thanks! 🙂

**Comment by sunli829** [comment]
I'm so sorry. 😂

**Comment by BratSinot** [comment]
> zed I forgot to submit.

It's ok =)

**Pull request merged**
