### PR TITLE
chore: sign the urls used for graphiql

### PR DESCRIPTION
**Pull request by maraisr**
Let's pin a version and sign the urls, as time goes on we can upgrade the versions/and sign new urls/find ways to automate this.

But this is fine for now.

---

Do we want to in a second PR deprecate grpahiqlv1?

fixes: #1046

### CODE REVIEW

**Comment by sunli829** [comment]
That's great! 👏

**Comment by NyCodeGHG** [comment]
Updating the versions could be done with !renovate's regex managers](https://docs.renovatebot.com/modules/manager/regex/), but i'm not sure about the hashes

**Comment by sunli829** [comment]
Do you know why these tests fail?

```
failures:
     http::graphiql_v2_source::tests::test_with_all_options
     http::graphiql_v2_source::tests::test_with_both_urls
     http::graphiql_v2_source::tests::test_with_only_url
```

**Comment by wolfv** [comment]
We are currently seeing CORS issues with the GraphiQL / unpkg version that is shipped. Maybe we can get this PR back on track?

**Comment by NyCodeGHG** [comment]
unpkg seems to have some issues right now. Even the status page is down: https://www.unpkg.com/status/

**Pull request closed without merging**
