### PR TITLE
Feature Generic Unions

### PR DESCRIPTION
**Pull request by TroyKomodo**
This PR adds support for using generics in unions and also adds the ability to specify concrete types.

The following will now compile.

```rs
struct MyObj<T> {
    value: T,
}

#[Object(
    concrete(name = "MyObjString", params(String)),
    concrete(name = "MyObjInt", params(i64))
)]
impl<T: Send + Sync + async_graphql::OutputType> MyObj<T> {
    async fn id(&self) -> i32 {
        10
    }

    async fn title(&self) -> String {
        "abc".to_string()
    }

    async fn value(&self) -> &T {
        &self.value
    }
}

#[derive(Union)]
#[graphql(concrete(name = "NodeInt", params(i64)))]
#[graphql(concrete(name = "NodeString", params(String)))]
enum Node<T: Send + Sync + async_graphql::OutputType> {
    MyObj(MyObj<T>),
}

struct Query;

#[Object]
impl Query {
    async fn node_int(&self) -> Node<i64> {
        Node::MyObj(MyObj {
            value: 10,
        })
    }

    async fn node_str(&self) -> Node<String> {
        Node::MyObj(MyObj {
            value: "abc".to_string(),
        })
    }
}

let query = r#"{
        nodeInt {
            ... on MyObjInt {
                value
            }
        }
        nodeStr {
            ... on MyObjString {
                value
            }
        }
    }"#;
let schema = Schema::new(Query, EmptyMutation, EmptySubscription);
assert_eq!(
    schema.execute(query).await.into_result().unwrap().data,
    value!({
        "nodeInt": {
            "value": 10,
        },
        "nodeStr": {
            "value": "abc",
        }
    })
);

println!("{}", schema.sdl());
```

The SDL output would be
```graphql
type MyObjInt {
        id: Int!
        title: String!
        value: Int!
}

type MyObjString {
        id: Int!
        title: String!
        value: String!
}

union NodeInt = MyObjInt

union NodeString = MyObjString

type Query {
        nodeInt: NodeInt!
        nodeStr: NodeString!
}


schema {
        query: Query
}
```

fixes: #1069 #978
supersedes: #983

### CODE REVIEW

**Comment by TroyKomodo** [comment]
The reason I added added this support was because in our application. Some actions can sometimes generate 2fa requests, for example logging in or changing password. It's annoying to have to have multiple union structs with different names but the same underlying logic. So instead having generic unions makes everything easier.

**Comment by TroyKomodo** [comment]
@sunli829 any suggestions for what i can do to get this merged into master?

**Comment by sunli829** [comment]
```
static_assertions = { git = "https://github.com/nvzqz/static-assertions-rs", rev = "a867e97a1b3c2e0c76b7a154abdf4e422b78e5f2" }
```
Is it possible to change to a published version?

**Comment by TroyKomodo** [comment]
We can but unfortunately, we wont be able to do the assertions. For some reason `static_assertions` is dead and there are unpublished changes on master.

**Comment by TroyKomodo** [comment]
Some issues i have with the current design of the generic stuff. 

```rs
struct MyObj<G> {
    _marker: std::marker::PhantomData<G>,
}

#[Object]
impl<G: Send + Sync> MyObj<G> {
    async fn id(&self) -> i32 {
        10
    }
}

struct MyObj2<G> {
    _marker: std::marker::PhantomData<G>,
}

#[Object]
impl<G: Send + Sync> MyObj2<G> {
    async fn id(&self) -> i32 {
        10
    }
}

#[derive(Union)]
#[graphql(concrete(name = "NodeMyObj", params("MyObj<G>"), bounds("G: Send + Sync")))]
enum Node<T: Send + Sync + async_graphql::OutputType> {
    Nested(MyObj2<T>),
    NotNested(T),
}
```

We have to specify the params and bounds this way. Because of the parser being unable to parse the arguments. Do you have any idea how I can make it behave like this?

```rs
#[derive(Union)]
#[graphql(concrete(name = "NodeMyObj", params(MyObj<G>), bounds(G: Send + Sync)))]
enum Node<T: Send + Sync + async_graphql::OutputType> {
    Nested(MyObj2<T>),
    NotNested(T),
}
```

**Comment by sunli829** [comment]
> We can but unfortunately, we wont be able to do the assertions. For some reason `static_assertions` is dead and there are unpublished changes on master.

It will prevent publishing to `crates.io`

**Comment by TroyKomodo** [comment]
@sunli829 What do you propose we do?

**Comment by sunli829** [comment]
```
static_assertions = { git = "https://github.com/nvzqz/static-assertions-rs", rev = "a867e97a1b3c2e0c76b7a154abdf4e422b78e5f2" }
```

here cannot be a git repository, which will cause `async-graphql` to fail to publish to `crates.io`.

**Comment by humb1t** [comment]
@TroyKomodo I suggest you to make a fork of `static_assertations` revision you are using as dependency, publish your fork to crates.io under another name, use crates.io version of your fork as dependency.

**Comment by TroyKomodo** [comment]
Sounds good, ill do that.

**Comment by sunli829** [comment]
```rust
#[derive(Union)]
#[graphql(concrete(name = "NodeMyObj", params("MyObj<G>"), bounds("G: Send + Sync")))]
enum Node<T: Send + Sync + async_graphql::OutputType> {
    Nested(MyObj2<T>),
    NotNested(T),
}
```

I think it's pretty good.

**Pull request merged**
