### PR TITLE
Add open / close WebSocket callbacks in warp subscription filter.

### PR DESCRIPTION
**Pull request by BratSinot**
Hello.

I ran into impossibilities to catch moment when opens and closes WebSocket connection (in my case it needed for metrics).
For now i only see way with callbacks.

### CODE REVIEW

**Comment by sunli829** [comment]
Thanks! 🙂

**Comment by sunli829** [comment]
Sorry, I think this code is not elegant enough, so I made an improvement again. Now you can use the `async_graphql_warp::graphql_subscription_upgrade` function to control the WebSocket connection more finely.

**Comment by sunli829** [comment]
You can now do like below:

```rust
warp::ws()
        .and(graphql_protocol())
        .map(move |ws: warp::ws::Ws, protocol| {
            let schema = schema.clone();
            let reply = ws.on_upgrade( move |websocket| {
                /// open
                graphql_subscription_upgrade(websocket, protocol, schema)
                /// close
            });
            warp::reply::with_header(
               reply,
               "Sec-WebSocket-Protocol",
               protocol.sec_websocket_protocol(),
           )
        });
```

**Comment by BratSinot** [comment]
> You can now do like below:
> 
> ```rust
> warp::ws()
>         .and(graphql_protocol())
>         .map(move |ws: warp::ws::Ws, protocol| {
>             let schema = schema.clone();
>             let reply = ws.on_upgrade( move |websocket| {
>                 /// open
>                 graphql_subscription_upgrade(websocket, protocol, schema)
>                 /// close
>             });
>             warp::reply::with_header(
>                reply,
>                "Sec-WebSocket-Protocol",
>                protocol.sec_websocket_protocol(),
>            )
>         });
> ```

Thanks!

**Pull request merged**
