### PR TITLE
Async-graphql 2.0

### PR DESCRIPTION
**Pull request by sunli829**
Do some simplifications on the api interface according to the suggestion of #261.

### CODE REVIEW

**Comment by sunli829** [comment]
Now it is necessary to move all `TransportConnection` and `websocket`  to the new `async-graphql-transport-ws` crate. Would you like to help complete this part of the work? @Koxiaet 🙂

**Comment by sunli829** [comment]
It looks very clear now, could you please help to see if there is anything that needs to be modified? 🙂 @Koxiaet

**Comment by Weasy666** [comment]
Will you also publish the Rocket integration with 2.0? Or is there anything else that needs to be done for the Rocket integration to be published?

**Comment by Koxiaet** [comment]
> Now it is necessary to move all TransportConnection and websocket to the new `async-graphql-transport-ws` crate. 

I don't think that's necessary - it's a fairly small task and more crates makes it harder for users to manager their `Cargo.toml`s. I think feature-gating it would be a better idea.

**Comment by sunli829** [comment]
> Will you also publish the Rocket integration with 2.0? Or is there anything else that needs to be done for the Rocket integration to be published?

There are few changes to modify the existing Rocket integration to Async-graphql 2.0, I will do this work. 3

**Comment by Weasy666** [comment]
Great news! 🚀😀

**Pull request merged**
