### PR TITLE
Initial add prelude module.

### PR DESCRIPTION
**Pull request by sunli829**
@nicolaiunrein  @phated @IcanDivideBy0 Please review. 😁

### CODE REVIEW

**Comment by phated** [comment]
I like it.

**Comment by nicolaiunrein** [comment]
The exports look about right and I think renaming is a good idea. But I think I would prefer "GQL_ID" over "GQLID" which still looks like a const but is a little better to read. Nevertheless I would stick to whatever the naming convention is.

**Comment by sunli829** [comment]
Thanks, let me change it to GQL_ID.

**Comment by IcanDivideBy0** [comment]
I have mixed feelings :/
I'd love to see a prelude mod but having different names in the prelude than in the crate root may confuse people?

**Comment by sunli829** [comment]
I think the usual way to use prelude should be like this?

```rust
use async_graphql::prelude::*;
```

**Comment by nicolaiunrein** [comment]
I agree that it might be confusing. But I think the underlying problem is that names in this library are too generic. What about prefixing all the generic pub types in this library and keep deprecated un-prefixed type-aliase around until the next major update in order not to break existing code? I think generic names like Object and Value etc should really be left for the user.

**Comment by IcanDivideBy0** [comment]
I agree with @nicolaiunrein renaming those types in the root crate while still exporting them with deprecated names seems better to me.
I can prepare a PR based on this one if we all agree

**Comment by sunli829** [comment]
I agree.
🍺🍺🍺🍺🍺🍺

**Comment by sunli829** [comment]
@IcanDivideBy0 
I am going to complete # 15 now, the changes will be relatively large, so it is best to wait for me to complete this first, otherwise it will be painful to merge the code.

**Comment by IcanDivideBy0** [comment]
@sunli829 ok!

**Comment by sunli829** [comment]
@IcanDivideBy0 
It was finally done because I was stuck for a long time with a small problem, you can continue. 😁

**Comment by IcanDivideBy0** [comment]
done in #78

**Pull request closed without merging**
