### PR TITLE
fix: handle the case where the response contains null for the enum 

### PR DESCRIPTION
**Pull request by ouertani**
Should handle the case where the response contains null for the enum

### CODE REVIEW

**Comment by xamgore** [comment]
Why?

**Comment by ouertani** [comment]
@xamgore I got error when enum from the graphql response is `null`

**Comment by xamgore** [comment]
Could you show the case, please? To understand, either it is a problem in the implementation and needs to be fixed, or just a problem in your source code.

**Review by Akremkadri — APPROVED** [review]

**Comment by ouertani** [comment]
@xamgore I tired to reproduce with the vanilla `async-graphql` crate and I confirm this is in issue in the related library and the source code I'm referring too. I will close this PR and thank you for the support.

**Pull request closed without merging**
