### PR TITLE
Implemented OutputType for tokio RwLock

### PR DESCRIPTION
**Pull request by boardmaster357**

### CODE REVIEW

**Comment by sunli829** [comment]
What do you think if it would be better to implement both for `tokio::sync::Mutex`? 😁

**Comment by boardmaster357** [comment]
Implementing for Mutex as well would be a good idea. Would you like me to revise the pull request? Should we just call the compile option "tokio"?

**Comment by sunli829** [comment]
> Implementing for Mutex as well would be a good idea. Would you like me to revise the pull request? Should we just call the compile option "tokio"?

Yes, and how about we named the feature `tokio-sync`? 😁

**Comment by boardmaster357** [comment]
Great idea. Will do.

**Comment by boardmaster357** [comment]
Thanks for the great improvemnts. I updated the pull request.

**Comment by sunli829** [comment]
Thank you so much! 😁

**Pull request merged**
