### PR TITLE
Updated to support Actix Web 4

### PR DESCRIPTION
**Pull request by zeroows**
Updating the version to the latest Beta version of Actix web 4.

I know Actix web is still in beta but I'm currently using it and I loved async-graphql and wanted to use it.

- Updated the integration for Actix web and the tests. 

Please feel free to use this as a reference when Actix web 4 is release.

thank you for your hard work in async-graphql

Regards,
Abdulrhman

### CODE REVIEW

**Comment by zeroows** [comment]
I'm still a rust noob but I would love to help in anyway I can.

**Comment by sunli829** [comment]
Thank you for your PR, Async-graphql already has an `actix-web-beta` branch, so did you do the same thing?

**Comment by zeroows** [comment]
No, I didn't see that branch. Sorry

**Comment by zeroows** [comment]
The branch uses **async-graphql 2.9.9**

**Comment by sunli829** [comment]
Thank you, I will merge it when `Actix-web v4` is released.

**Comment by sunli829** [comment]
Since the `actix-web-v4-beta` branch has been updated, I will close it, thank you!🙂 @zeroows

**Pull request closed without merging**
