### PR TITLE
feat: support bson v2.0.0-beta

### PR DESCRIPTION
**Pull request by flisky**
This could be merged after the final release :)

### CODE REVIEW

**Comment by sunli829** [comment]
When `bsonv2` is finally released, I think we can remove support for `bsonv1`, what do you think?

**Comment by flisky** [comment]
I'm okay with that, but it should bump the version due to a breaking change?

**Comment by AurelienFT** [comment]
To add bson recommend 2.0.0-beta.1 in their README.md : https://github.com/mongodb/bson-rust

**Comment by flisky** [comment]
Aha, thank you for reminding me that bson -> mongo -> tokio dependency chain, so it's perhaps a expected breaking change. I'll update this PR shortly.

**Comment by flisky** [comment]
Could you please take another look, @sunli829? Thanks!

**Comment by sunli829** [comment]
Thank you so much! 🙂

**Comment by AurelienFT** [comment]
@sunli829 Can you make a feature realease so that we can use it in our project please ? :) And thanks again for your reactivity and your kindness with your community

**Comment by AurelienFT** [comment]
Released in 2.9.3.

**Pull request merged**
