### PR TITLE
Add support for cbor

### PR DESCRIPTION
**Pull request by Erik1000**
A while back we discussed the ability to use cbor as encoding. Back then, we got that to work and used it since on our fork. I thought that we could make a PR too.

# Note

We use it to build a graphql server and haven't encountered any errors *yet*. Multipart (for the file upload extension) probably won't work just yet, because it still uses serde_json.

### CODE REVIEW

**Comment by Erik1000** [comment]
Related issue: https://github.com/async-graphql/async-graphql/issues/569

**Comment by sunli829** [comment]
Thank you very much, it looks great! 🙂

**Comment by Erik1000** [comment]
forgot to format that i guess

**Comment by sunli829** [comment]
> forgot to format that i guess

I will solve it, and I will add a feature called `cbor`, what do you think?

**Comment by Erik1000** [comment]
> I will solve it, and I will add a feature called cbor, what do you think?
seems like a good idea :+1:

**Comment by Erik1000** [comment]
Should I merge your master into our fork so clippy passes(see latest commit comment)?

**Comment by sunli829** [comment]
Yes, you can deref `Bytes` to `&[u8]`.

https://docs.rs/futures/0.3.17/futures/io/trait.AsyncRead.html#impl-AsyncRead-for-%26%27_%20%5Bu8%5D

**Comment by sunli829** [comment]
I have merged into the `master`.

**Comment by sunli829** [comment]
> Also I'm currently looking into the multipart code and there's a problem with multer:
I want to reduce code duplication so here I want to reuse the receive_batch_body method.

You can create a new PR to continue to improve this issue. 🙂

**Comment by Erik1000** [comment]
I'll do :+1:

**Pull request merged**
