### PR TITLE
Update axum integration version

### PR DESCRIPTION
**Pull request by tomerze**
Makes our axum integration work with axum 0.6.* which introduced some breaking changes.

### CODE REVIEW

**Comment by tomerze** [comment]
We should probably wait until axum 0.6.* is fully released before we merge this.

**Comment by sunli829** [comment]
Thanks, it will be merged when `Axum 0.6` is released. 🙂

**Comment by dspicher** [comment]
axum 0.6.0 has been released :rocket:

**Comment by sunli829** [comment]
Thanks! 🙂

**Pull request merged**
