### PR TITLE
Added u32 as ScalarType

### PR DESCRIPTION
**Pull request by MidasLamb**

### CODE REVIEW

**Comment by sunli829** [comment]
Thank you.

**Comment by mwilliammyers** [comment]
Why is `Int64` being mapped to `u32`?

**Comment by sunli829** [comment]
I made some changes.

u32 -> UInt64
u64 -> UInt64

**Comment by MidasLamb** [comment]
Sorry for the late reply. 
@mwilliammyers, I based it on the implementation of u64, but that needed to be corrected as wel it seems

**Pull request merged**
