### PR TITLE
Ongoing english translations

### PR DESCRIPTION
**Pull request by Ejhfast**
So far I've translated section 4 and section 5 since @DataCorrupted started already with the Types section

Re: https://github.com/async-graphql/async-graphql/issues/34

### CODE REVIEW

**Comment by Ejhfast** [comment]
Added section 6

**Comment by Ejhfast** [comment]
Added section 7. I'm not familiar with Apollo Federation beyond the high level concept, so someone should probably sanity check that. 

That wraps up everything besides the Types section I think. Though I think many things can be improved beyond translation, this should be good for merge after a sanity check.

**Comment by sunli829** [comment]
Thank you for using your precious time to help me do these tasks, and they have done so well. If you have any questions about the use of this library later, please let me know and I will do my best to help you. 😁

**Comment by sunli829** [comment]
@IcanDivideBy0  Also thank you for your review. 😁

**Pull request merged**
