### PR TITLE
Prefer TryFrom to TryInto for ID

### PR DESCRIPTION
**Pull request by IcanDivideBy0**
#71 was merged a bit fast :D
Generally speaking `TryFrom` is more general than `TryInto` (cause `TryFrom` implies `TryInto`), so this should gives a bit more flexibility, like using the try_from as a closure
```rust
vec![ /* ... */ ]
    .iter()
    .map(ID::try_trom)
    .collect::<Result<usize, _>>()
```

### CODE REVIEW

**Comment by sunli829** [comment]
All right.😂

**Comment by IcanDivideBy0** [comment]
@sunli829 don't merge this right now

**Comment by IcanDivideBy0** [comment]
@sunli829 that's good now.
Since `ID` does not implement `fmt::Display` anymore, converting an `ID` to a cursor required more steps, now we can also convert `ID` into a `Cursor` easily which I believe is also a common use case.

**Comment by IcanDivideBy0** [comment]
@sunli829 Thanks a lot for the invitation to collaborate on the project, I really appreciate! :D

**Comment by sunli829** [comment]
Let's work together on rust's best graphql library.🤝

**Pull request merged**
