### PR TITLE
export type directive even federation is disabled

### PR DESCRIPTION
**Pull request by shmurakami**
There is `type directive` feature however it looks usable only when federation is enabled. I want to use type directive and export to SDL.
This behavior matches this document https://async-graphql.github.io/async-graphql/en/custom_directive.html#type-system-directives I think.

### CODE REVIEW

**Review by dbanty — APPROVED** [review]
Looks good to me once CI passes

**Comment by shmurakami** [comment]
@dbanty Thank you for your review! Fixed tests and passed tests and clippy on my local.

**Review by dbanty — APPROVED** [review]

**Comment by shmurakami** [comment]
@sunli829 @dbanty Hi, how is it going? :)

**Comment by sunli829** [comment]
@shmurakami @dbanty thanks! 🙂

**Comment by shmurakami** [comment]
clippy failed due to my branch is bit outdated. Applied master branch.

**Review by dbanty — APPROVED** [review]

**Comment by shmurakami** [comment]
@sunli829 @dbanty Do I have to do something to merge?

**Comment by dbanty** [comment]
I think it's good to go, but I don't think I have the authority to click the "merge" button 😅. So waiting on @sunli829 (if you want me to merge future PRs that I review, let me know!)

**Pull request merged**
