### PR TITLE
Add fuzzer running on parse_query

### PR DESCRIPTION
**Pull request by 5225225**
This is a very basic fuzzer that can be ran with https://github.com/rust-fuzz/cargo-fuzz.

### CODE REVIEW

**Comment by 5225225** [comment]
Pinging @sunli829, this is how I found the issue I sent an email about a few days back (on the 3rd). Did you receive that? It's just a DoS so not terribly sensitive.

**Comment by sunli829** [comment]
Sorry, I haven't checked email these days. 🙂

**Comment by 5225225** [comment]
No worries :)

I sent a followup with a much simpler test case yesterday too, you can ignore the first one.

**Comment by 5225225** [comment]
That doesn't look related to the changes, badge says CI on master is failing.

`cargo test` on master fails too for me.

**Comment by sunli829** [comment]
I have fixed that in `v4.0.7`, thanks a lot! @5225225

**Pull request merged**
