### PR TITLE
Add tests for Input Validators

### PR DESCRIPTION
**Pull request by kevinschoonover**
Adds tests for all Input Validators to help solve issues like #113. 

Roadmap for what validators will be tested:
+ **String**
  - [X] StringMinLength
  - [X] StringMaxLength
  - [X] Email
  - [X] MAC
+ **Int**
  - [X] IntEqual
  - [X] IntNonZero
  - [X] IntGreaterThan
  - [X] IntLessThan
  - [X] IntRange
+ **List**
  - [X] ListGreaterThan
  - [X] ListLessThan
+ **Operators**
  - [x] OR operator
  - [x] AND operator

Problems noticed when testing code:
+ Email validation allows certain invalid emails to be accepted via the regex.

### CODE REVIEW

**Comment by sunli829** [comment]
It looks pretty good, thank you. 😁

**Comment by kevinschoonover** [comment]
@sunli829 when I was testing the email validator, there seems to be some invalid emails that are being accepted by the regex. See the [commented out tests](https://github.com/async-graphql/async-graphql/pull/119/files#diff-0836466abf28a54d59e97dbc066951d9R252). It could very well be the source I was using is incorrect.

**Comment by kevinschoonover** [comment]
They also seem like some pretty extreme edge cases so even if they are suppose to be invalid, is that something that should be handled?

**Comment by sunli829** [comment]
If you are free, can you help me make it more accurate?

> They also seem like some pretty extreme edge cases so even if they are suppose to be invalid, is that something that should be handled?

I don’t think it ’s a big problem, but if you ’re free, can you help me make it more accurate? 😁

Thanks again, your test is too comprehensive.

**Comment by kevinschoonover** [comment]
I can try to take a look after I complete this PR. Another problem I came across is when I try to use negative numbers for bounds on any integer validator like with the following code:
```rust
#[InputObject]                                      
struct InputIntRange {                                
    #[field(validator(IntRange(min = "-1", max = "5")))]
    pub id: i32,
}¬                                                       
```
I receive the following error:
```
error[E0282]: type annotations needed
   --> tests/input_validators.rs:643:5
    |
643 |     #[InputObject]
    |     ^^^^^^^^^^^^^^ this method call resolves to `T`
    |
    = note: type must be known at this point
    = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I can also try and take a look at it after completing this PR. I should only have list validators to go which should hopefully be pretty quick.

**Comment by sunli829** [comment]
> I can try to take a look after I complete this PR. Another problem I came across is when I try to use negative numbers for bounds on any integer validator like with the following code:
> 
> ```rust
> #[InputObject]                                      
> struct InputIntRange {                                
>     #[field(validator(IntRange(min = "-1", max = "5")))]
>     pub id: i32,
> }¬                                                       
> ```
> 
> I receive the following error:
> 
> ```
> error[E0282]: type annotations needed
>    --> tests/input_validators.rs:643:5
>     |
> 643 |     #[InputObject]
>     |     ^^^^^^^^^^^^^^ this method call resolves to `T`
>     |
>     = note: type must be known at this point
>     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
> ```
> 
> I can also try and take a look at it after completing this PR. I should only have list validators to go which should hopefully be pretty quick.

I fixed this bug in the main branch. 😃

**Comment by kevinschoonover** [comment]
Sorry for all of the messages @sunli829, I noticed another problem where `and` actually performs `or` and `or` actually performs `and`. The sample case I have is:
```rust
#[Object]                                                               
impl QueryRoot {                                                        
    async fn field_parameter(                                           
        &self,                                                          
        #[arg(validator(and(Email, MAC(colon = "false"))))] _id: String,
    ) -> bool {                                                         
        true                                                            
    }                                                                   
                                                                        
    async fn input_object(&self, _input: InputOrValidator) -> bool {    
        true                                                            
    }                                                                   
}                                                                       
```

returns successfully if I pass in email@example.com, but
```rust
#[Object]                                                              
impl QueryRoot {                                                       
    async fn field_parameter(                                          
        &self,                                                         
        #[arg(validator(or(Email, MAC(colon = "false"))))] _id: String,
    ) -> bool {                                                        
        true                                                           
    }                                                                  
                                                                       
    async fn input_object(&self, _input: InputOrValidator) -> bool {   
        true                                                           
    }                                                                  
}                                                                      
```

returns the following error with the same input

```
---- test_input_validator_operator_or stdout ----
thread 'test_input_validator_operator_or' panicked at 'Schema returned error wi
th test case = "email@example.com": Rule { errors: [RuleError { locations: [Pos
(1:17)], message: "Invalid value for argument \"id\", invalid MAC format" }] }'
, tests/input_validators.rs:1461:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I can take a crack at this also after the PR, but I thought I would document it here to see what you wanted to do about it.

**Comment by sunli829** [comment]
I will solve this problem now.

**Comment by sunli829** [comment]
Tell me if you have any questions. 😁

**Comment by sunli829** [comment]
> Please also let me know if this is due to me doing something wrong.

Sorry, I made a stupid mistake.
I really appreciate your meticulous testing, I have fixed this issue on the main branch. 😁

**Comment by kevinschoonover** [comment]
@sunli829 I'm gonna clean up the commit history, but should be ready for a full review

**Comment by kevinschoonover** [comment]
> Sorry, I made a stupid mistake.
> I really appreciate your meticulous testing, I have fixed this issue on the main branch. grin
Not a problem at all.

It's absolutely my pleasure, I am glad I can help in a small way contribute and improve to all the effort you are putting into this library.

**Comment by sunli829** [comment]
Thank you so much for adding quality test code and fixing a lot of bugs. 😄

**Pull request merged**
