### PR TITLE
Add possibility to use @defer/@stream on a fragment spread or an inline fragment

### PR DESCRIPTION
**Pull request by sync**
This is just to please the relay compiler, it doesn't stream the fragment... I am not sure how to do this at the moment.

PS: feel free to close this if it makes no sense

### CODE REVIEW

**Comment by sunli829** [comment]
This is not really supporting @defer on the Fragment.

**Comment by sync** [comment]
Agreed i don't know what I am doing :-)

**Comment by sync** [comment]
Just checked, indeed with this the response isn't streamed back but i get a full json instead.

**Comment by sync** [comment]
the end goal is to stream those fragments (which isn't working now) and to provide the label back on the subsequent chunk:

```
{"data":{"node":{"__typename":"User","id":"726995694","timeline_list_feed_units":{"edges":[{"node": 
.....
{"label":"ProfileCometTimelineFeed_user$stream$ProfileCometTimelineFeed_user_t
```

**Comment by sync** [comment]
We will reopen this once when standard is properly defined. Thanks for your help

**Pull request closed without merging**
